In [29]:
import numpy as np
import torch
import torch.nn as nn

def custom_batch_norm1d(input_tensor, eps):
    # print(input_tensor.shape)
    gamma = 1
    beta = 0
    N = input_tensor.shape[0]
    normed_tensor = torch.zeros(input_tensor.shape)
    print('eps:',eps)
    # print('input:',input_tensor[0,:])
    # print('square:',(input_tensor[0,:]-1)**2)
    # print('sigma:',torch.sum((input_tensor[0,:]-1)**2))
    for i in range(input_tensor.shape[1]):
        # print ('i:', i)
        E = torch.sum(input_tensor[:,i])/N
        sigma_square = torch.sum((input_tensor[:,i]-E)**2)/N
        print('E:', E)
        print('sigma_square:', sigma_square)
        z = (input_tensor[:,i]-E)/torch.sqrt(sigma_square + eps)
        # print('z:', z)
        normed_tensor[:,i] = z #*gamma + beta
        # print('normed_tensor:', normed_tensor)
    print('input_tensor:\n', input_tensor)
    print('normed_tensor:\n', normed_tensor)
    return normed_tensor


input_tensor = torch.Tensor([[0.0, 0, 1, 0, 2], [0, 1, 1, 0, 10]])
# input_tensor = torch.Tensor([[1, 2, 3, 4, 5], [0, 1, 1, 0, 10]])
batch_norm = nn.BatchNorm1d(input_tensor.shape[1], affine=False)

# Проверка происходит автоматически вызовом следующего кода
# (раскомментируйте для самостоятельной проверки,
#  в коде для сдачи задания должно быть закомментировано):
# import numpy as np
all_correct = True
for eps_power in range(10):
    eps = np.power(10., -eps_power)
    batch_norm.eps = eps
    batch_norm_out = batch_norm(input_tensor)
    print('correct batch norm:\n', batch_norm_out)
    custom_batch_norm_out = custom_batch_norm1d(input_tensor, eps)

    all_correct &= torch.allclose(batch_norm_out, custom_batch_norm_out)
    all_correct &= batch_norm_out.shape == custom_batch_norm_out.shape
print(all_correct)

correct batch norm:
 tensor([[ 0.0000, -0.4472,  0.0000,  0.0000, -0.9701],
        [ 0.0000,  0.4472,  0.0000,  0.0000,  0.9701]])
eps: 1.0
E: tensor(0.)
sigma_square: tensor(0.)
E: tensor(0.5000)
sigma_square: tensor(0.2500)
E: tensor(1.)
sigma_square: tensor(0.)
E: tensor(0.)
sigma_square: tensor(0.)
E: tensor(6.)
sigma_square: tensor(16.)
input_tensor:
 tensor([[ 0.,  0.,  1.,  0.,  2.],
        [ 0.,  1.,  1.,  0., 10.]])
normed_tensor:
 tensor([[ 0.0000, -0.4472,  0.0000,  0.0000, -0.9701],
        [ 0.0000,  0.4472,  0.0000,  0.0000,  0.9701]])
correct batch norm:
 tensor([[ 0.0000, -0.8452,  0.0000,  0.0000, -0.9969],
        [ 0.0000,  0.8452,  0.0000,  0.0000,  0.9969]])
eps: 0.1
E: tensor(0.)
sigma_square: tensor(0.)
E: tensor(0.5000)
sigma_square: tensor(0.2500)
E: tensor(1.)
sigma_square: tensor(0.)
E: tensor(0.)
sigma_square: tensor(0.)
E: tensor(6.)
sigma_square: tensor(16.)
input_tensor:
 tensor([[ 0.,  0.,  1.,  0.,  2.],
        [ 0.,  1.,  1.,  0., 10.]])
normed_tens